version: "2"
linters:
  enable:
    - errcheck
    - ineffassign
    - staticcheck
    - unused

  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
      disable-default-exclusions: true
      exclude-functions:
        - (*os.File).Close
        - (io.Closer).Close
        - fmt.Print
        - fmt.Printf
        - fmt.Println
        - fmt.Fprint
        - fmt.Fprintf
