---
name: Run Gosec
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

env:
  GO_VERSION: 1.18

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GOROOT: $(go env GOROOT)
    steps:
      - name: Set up Go 1.x
        id: go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Check out code
        uses: actions/checkout@v2

      - name: Show project files after make
        run: tree .

      - name: Set Go environment variables
        id: goroot
        run: |
          echo "GOROOT=$(go env GOROOT)" >> $GITHUB_ENV

      - name: Run Gosec Security Scanner
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          gosec -conf .gosec.json ./...