name: "Main"

on:
  push:
    branches:
      - main

  # pull_request:
  #   branches:
  #     - main

  workflow_dispatch:

env:
  GO_VERSION: 1.18

permissions:
  security-events: write
  actions: read
  contents: read
  pull-requests: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        id: go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Check out code
        uses: actions/checkout@v2

      - name: Show project files before make
        run: tree .

      - name: Test
        run: make test

      - name: Show project files after make
        run: tree .

      - name: codecov coverage report
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: ./coverage.out

      - name: Remove artifacts
        run: make clean